bts_rpc_port: 5691
bts_rpc_user: user
bts_rpc_password: pass

dvs_rpc_port: 5691
dvs_rpc_user: user
dvs_rpc_password: pass

pls_rpc_port: 5691
pls_rpc_user: user
pls_rpc_password: pass

bts_faucet_account: pls_angel
dvs_faucet_account: pls_angel
pls_faucet_account: pls_angel

faucet_refcode_prefix: PLS
registrations_limit: 1

oauth:
  facebook:
    app_id: 111
    secret: 222
  twitter:
    app_id: 111
    secret: 222
  linkedin:
    app_id: 111
    secret: 222
  google:
    app_id: 111
    secret: 222
  github:
    app_id: 111
    secret: 222
  reddit:
    app_id: 111
    secret: 222
  weibo:
    app_id: 111
    secret: 222
  qq:
    app_id: 111
    secret: 222

meta_wb_webmaster: 111
meta_qc_admins: 111
