bts_rpc_port: 5691
bts_rpc_user: user
bts_rpc_password: pass

dvs_rpc_port: 5691
dvs_rpc_user: user
dvs_rpc_password: pass

bts_faucet_account: faucet
dvs_faucet_account: faucet

faucet_refcode_prefix: NNN
registrations_limit: 1

oauth:
  facebook:
    app_id: 111
    secret: 222
  twitter:
    app_id: 111
    secret: 222
  linkedin:
    app_id: 111
    secret: 222
  google:
    app_id: 111
    secret: 222
  github:
    app_id: 111
    secret: 222
  reddit:
    app_id: 111
    secret: 222
  weibo:
    app_id: 111
    secret: 222
  qq:
    app_id: 111
    secret: 222

meta_wb_webmaster: 111
meta_qc_admins: 111

default_url: faucet.bitshares.org
default_port: 3000

mandrill:
  host: smtp.mandrillapp.com
  user_name: user_name
  password: password

mailchimp:
  api_key: 123
  list_id: 123

exception_notification:
  sender_address: faucet@example.com
  exception_recipients: admin@example.com
